from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
import models, schemas, auth, database

router = APIRouter()
#route on clickong the register button
@router.post("/register")
def register(user: schemas.UserCreate, db: Session = Depends(database.get_db)):
    #Checking if user already exists
    existing_user = db.query(models.User).filter(models.User.username == user.username).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Username already registered")
    #Hashing the password
    hashed = auth.hash_pass(user.password)
    #Create a new User object (Row)
    new_user = models.User(username=user.username, hashed_password=hashed)
    #Saving to Database throught the session
    db.add(new_user)
    db.commit()
    db.refresh(new_user) # Retrieves the ID generated by Postgres
    return {
        "message":"you are registered successfully"
    }
#route on clicking the login button
@router.post("/login")
def login(user_credentials: schemas.UserCreate, db: Session = Depends(database.get_db)):
    #Fetching user from DB
    user = db.query(models.User).filter(models.User.username == user_credentials.username).first()
    #here the user is an initialised object of class User in the models.py file
    #Checking existence and verifying password
    if not user or not auth.verify_pass(user_credentials.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED, 
            detail="Invalid credentials"
        )
    
    #Generating the JWT token
    access_token = auth.create_jwt_token(data={"user_id": user.id})
    
    return {"access_token": access_token, "token_type": "bearer"}